modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "AGPL-3.0 license"

[[mods]]
modId = "epimorphism"
version = "${version}"
displayName = "Epimorphism"
credits = "All members of the GregTech CN Community"
authors = ""
description = '''
A huge addon for GregTechCEu Modern.
'''
#logoFile = ""

[[dependencies.epimorphism]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.epimorphism]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.epimorphism]]
modId = "gtceu"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"