name: Nightly Build For Epimorphism-Modern
on:
  push:
    paths:
      - .github/workflows/**
      - src/**
      - gradle/scripts/**
      - build.gradle
      - gradle.properties
      - settings.gradle
    branches:
      - main

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/build.yml

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4.1.7
        id: 'artifact'

      - name: Read Properties
        id: 'properties'
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'mod_id mod_name mod_version'

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: "Epimorphism-Modern Nightly Build.${{ vars.GITHUB_RUN_NUMBER }}"

          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: "${{ steps.var.properties.mod_version }}_build_${{ vars.GITHUB_RUN_NUMBER }}"
          github-generate-changelog: true
          github-prerelease: true

          files: "${{ steps.artifact.outputs.download-path }}/**/${{ steps.var.properties.mod_id }}-*.jar"
